### PR TITLE
Fix Compile Error

### PR DESCRIPTION
**Pull request by TingyiChen**
Correct the path of ims.apk

### CODE REVIEW

**Comment by dev-harsh1998** [comment]
@TingyiChen  Our friend @Silentlys  Have updated Vendor is there any progress ?

**Comment by dev-harsh1998** [comment]
compiled rom booted ?

**Comment by dev-harsh1998** [comment]
@Silentlys now rom compiles ?

**Comment by dev-harsh1998** [comment]
@Silentlys is rom isnt booting can you please make a build ? it isnt booting form me

**Comment by TingyiChen** [comment]
i am compiling.the rom i built yesterday can't boot

**Comment by TingyiChen** [comment]
@dev-harsh1998

**Comment by dev-harsh1998** [comment]
Where was it stuck @TingyiChen

**Comment by TingyiChen** [comment]
i don't know.i can't see bootanimation

**Comment by dev-harsh1998** [comment]
Send me the boot.img

**Comment by dev-harsh1998** [comment]
@TingyiChen Send me boot.img from your rom

**Comment by TingyiChen** [comment]
wait.i am uploading.but i am not sure weather it is

**Comment by TingyiChen** [comment]
ok i found the correct one

**Comment by TingyiChen** [comment]
https://mega.nz/#!4UEDkBya!RQLybI3Nv65TcZqjXxWMDych7VGPICQqpGoBxbzAAOs @dev-harsh1998

**Comment by TingyiChen** [comment]
you can connect to my ubuntu via vnc now

**Comment by TingyiChen** [comment]
ip:171.83.217.86
port:5900
password:115020

**Comment by TingyiChen** [comment]
The password of my system is 4221261972

**Comment by TingyiChen** [comment]
You can add my telegram.my phone number is +8613986527267

**Comment by TingyiChen** [comment]
@dev-harsh1998

**Comment by TingyiChen** [comment]
Are u online ?

**Comment by TingyiChen** [comment]
@dev-harsh1998 harsh,i found the kernel of a6010 can boot on k31-t3(k3s),but the wifi doesn't work.

**Comment by dev-harsh1998** [comment]
@TingyiChen So my CM13 compiled from my Tree booted with a6010 kernel ?

**Comment by dev-harsh1998** [comment]
thanks for the news

**Comment by TingyiChen** [comment]
still under bootloop

**Comment by TingyiChen** [comment]
the a6010 kernel can work on offical rom

**Comment by TingyiChen** [comment]
flour_mo said that its the problem of ramdisk

**Comment by TingyiChen** [comment]
i am so sorry that you misunderstand what i said.....

**Comment by TingyiChen** [comment]
my phone has bricked.....

**Comment by TingyiChen** [comment]
i flashed k3's emmc_appsboot.mbn,then reboot it.now it can't display splash.....

**Comment by TingyiChen** [comment]
@dev-harsh1998 help me....

**Comment by dev-harsh1998** [comment]
Upstream Your Kernel For m compability it will boot then

**Comment by TingyiChen** [comment]
@dev-harsh1998 but my phone is brick now.....I can't use QFIL to flash it because i can't see 9008 Diagnostic Port....I have to fix it now.and i will go to school today.so i can't compile it now.....

**Pull request closed without merging**
